//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseInventory.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWarehouses
    {
        public int WarehousesId { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<System.Guid> WarehouseGuid { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
